version: "3.9"

services:
  zammad:
    build:
      context: .
      args:
        COMMIT_SHA: 6f75c6f8e85c66e2117dfe978d4f4df2ab3a19c7
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/opt/zammad
      - /opt/zammad/node_modules
    depends_on:
      - redis
      # - postgres!!
    command: /bin/sh -c "rm -f /opt/zammad/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  redis_data:
