default: &default
  pool: 50
  encoding: utf8
  adapter: postgresql
  host: postgres.railway.internal
  port: 5432
  username: postgres
  password: wCujthKlbUmIsPQqqiebCQicMwLGWexE

production:
  <<: *default
  database: railway

development:
  <<: *default
  database: railway

test:
  <<: *default
  database: zammad_test
